version: "1.0"
services:
  # PostgreSQL Database Service
  db:
    image: postgres:13-alpine
    container_name: Postgres_DB
    environment:
      POSTGRES_DB: bdhv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bdhv-network-local

  # Backend Service
  backend:
    build: .
    container_name: bdhv_server
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bdhv
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bdhv-network-local

# Volume for persistent PostgreSQL and Redis storage
volumes:
  db_data:

# Define custom Docker network
networks:
  bdhv-network-local:
    driver: bridge