version: '1.0'
services:
  # PostgreSQL Database Service
  db:
    image: postgres:13-alpine
    container_name: Postgres_DB
    environment:
      POSTGRES_DB: bdhv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bdhv-network-local

  # Redis Cache Service
  cache:
    image: redis:6-alpine
    container_name: Redis_Cache
    ports:
      - "6379:6379"
    networks:
      - bdhv-network-local
    volumes:
      - redis_data:/data

#  # Backend Service
#  backend:
#    build: .
#    container_name: bdhv_server
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bdhv
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - db
#    networks:
#      - bdhv-network-local

# Volume for persistent PostgreSQL and Redis storage
volumes:
  db_data:
  redis_data:

# Define custom Docker network
networks:
  bdhv-network-local: